### ISSUE TITLE
v12 Support

### ISSUE THREAD

**Issue by GregsGrog** [cirrahn/foundry-polmap#19]
Hello!

There seems to be some incompatibilities with V12 is, is the module likely to be updated. No rush of course!

Thanks for providing something super usefull!

**Comment by GregsGrog** [comment]
`Error: Error thrown in hooked function '' for hook 'renderSceneControls'. Cannot set properties of null (setting 'tint')
    at Hooks.onError (foundry.js:654:24)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁Hooks.onError#lib-wrapper (listeners.js:138:11)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:187:52)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at SceneControls._callHooks (foundry.js:5917:13)
    at SceneControls._render (foundry.js:5878:10)Caused by: TypeError: Cannot set properties of null (setting 'tint')
    at module.js:921:44
    at Array.forEach (<anonymous>)
    at PoliticalMapLayer.setPreviewTint (module.js:921:12)
    at PoliticalMapLayer.setActiveTool (module.js:886:8)
    at Object.fn (module.js:1511:17)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at SceneControls._callHooks (foundry.js:5917:13)
    at SceneControls._render (foundry.js:5878:10)`

**Comment by cirrahn** [comment]
The module needs a rewrite to work in v12+. I have been dragging my heels on this as I am still mainly using v11!

**Comment by GregsGrog** [comment]
I thought this might be the case, for now will downgrade to V11 since I cant do without it!

**Comment by sipcogames** [comment]
Was also looking for V12 support with no specific rush. XD Will keep an eye on the project until then :)

**Comment by krazmuze** [comment]
V12 has been stable since May so it is safe to switch from V11 except for this.  
UI loads it just gives that null console error trying to paint the overlay.

**Comment by Mermut** [comment]
Any news if an update for v12 is on the horizon?

**Comment by cirrahn** [comment]
No, sorry! I have not had free time to work on this module. It is likely that v13 will be released before I do, at which point I will re-assess: this module may be defunct if there are new scene region/map tools available by way of, for example, Ember back-ports.

**Comment by FatherJ-ct** [comment]
I 2nd sipcogames comment of would like to see this updated though no rush and keeping eye out for update or alternative. Definitely miss being able to use this module with having moved to v12 (very useful).

**Comment by TitanicViking** [comment]
Definitely will miss this mod if its not going to be updated. Helped visuals for territories in my werewolf game. Can anyone recommend any similar mods that are compatible with fvtt 12?

**Comment by cirrahn** [comment]
I have not tried it, but [Ripper's Hexplorer](https://youtu.be/tdvmX9qIx80?t=29) may be worth checking out!

**Comment by apocolips18** [comment]
For sure hoping to use this plugin in the future, as it would be perfect for showing faction regions in my Fallout group ^_^
